name: Test push events
on:
  push:
    branches: 
      - main
    paths:
      - .github/workflows/test3.yml
jobs:
  test_push_event:
    if: |
      github.event_name == 'push' &&
      github.ref_name == 'master' &&
      github.repository_owner == 'test_workflow'
    run_on: ubuntu-20.04
    steps:
      - name: Test Shell
        shell: bash
        run: echo "Hi"
